"""add_profile_fields_and_friend_requests

Revision ID: 40d8e2ec1d08
Revises: e5f6a7b8c9d0
Create Date: 2026-07-01 18:34:50.924624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d8e2ec1d08'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('home_gym', sa.String(), nullable=True))
    op.add_column('users', sa.Column('favorited_route_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'routes', ['favorited_route_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'favorited_route_id')
    op.drop_column('users', 'home_gym')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
